config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  resources :goodspots
  resources :locations, only: [:show]
  resources :sessions,  only: [:index, :new, :create, :destroy]
  resources :users,     only: [:new, :create, :show, :destroy]
  get '/login', to: 'sessions#new'
end

app/models/goodspot.rb
class Goodspot < ActiveRecord::Base
  belongs_to :user
  belongs_to :location

  after_validation :geocode
  geocoded_by :place

  def place
    address || (name + ", #{location.city}, #{location.state}")
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :users
  has_many :goodspots
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :location
  has_many   :goodspots

  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

     # Make the current_user method available to views, not just controllers!
    helper_method :current_user

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authorize
      redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
    end

end

app/controllers/goodspots_controller.rb
class GoodspotsController < ApplicationController


  def index
    # we filter the list of goodspots
    @goodspots = Goodspot.all

    if params[:location] != ""
      @goodspots = @goodspots.select{|gs| gs.location_id == params[:location].to_i}
    end
    if params[:category] != ""
      @goodspots = @goodspots.select{|gs| gs.category == params[:category]}
    end

    @locations_options = Location.all.map { |location| ["#{location.city}, #{location.state}", location.id] }
    @categories = ["Food/Drink", "Live Venue", "Movies", "Museum", "Tours", "Art/Music", "Misc.", "Surfing"] #.map {|c| [c, c] }
  end




  def new
    @goodspot = Goodspot.new

    @states = Location.all.map { |l| l.state }
    @cities = Location.all.map { |l| l.city }

    @categories = ["Food/Drink", "Live Venue", "Movies", "Museum", "Tours", "Art/Music", "Misc.", "Surfing"]
  end



  def create
    if current_user.goodspots.create(goodspot_params)
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end



  def show
    @goodspot = Goodspot.find(params[:id])
  end


  def edit
    @states = Location.all.map { |l| l.state }
    @cities = Location.all.map { |l| l.city }
    @categories = ["Food/Drink", "Live Venue", "Movies", "Museum", "Tours", "Art/Music", "Misc.", "Surfing"]
    @goodspot = Goodspot.find(params[:id])
  end



  def update
    @goodspot = Goodspot.find(params[:id])
    if @goodspot.update(goodspot_params)
      flash[:notice] = "Goodspot Succefully Updated!"
      redirect_to goodspot_path(@goodspot)
    end
  end



  def destroy
    Goodspot.find(params[:id]).delete
    flash[:notice] = 'Goodspot Deleted'
    redirect_to user_path(current_user)
  end



    private
    # Implement Strong Params
    def goodspot_params
      params.require(:goodspot).permit(:name, :description, :address, :state, :city, :category, :url, :image)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
  end

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id),
      notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid login credentials - try again!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, only: [:show, :edit]
  before_action :authorize,    only: [:show, :edit]



  def show

    if
      params[:id] == session[:user_id]
      @user = @current_user
    else
      @user = User.find(params[:id])
    end
  end



  def new
    @user = User.new
  end



  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
      flash[:notice] = "You have successfully signed up!"
      else
        render 'new'
    end
  end

  def destroy
    User.find(params[:id]).delete
    session[:user_id] = nil
    flash[:notice] = 'Account Deleted'
    redirect_to new_user_path
  end



  private
  # Implement Strong Params
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end



  def authenticate
    redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
  end




  def authorize
    @user = User.find(current_user)
    redirect_to root_path if @user != current_user
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/goodspots/edit.html.erb
<p><%=@goodspot.name%></p>
<p><%=@goodspot.description%></p>


<div class="container">

<%= form_for @goodspot do |f| %>

  <div class="form-group"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= f.label :name, "Title", class: "control-lable" %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group container">
    <%= f.label :description, "Description",class: "control-lable" %>
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
    <%= f.label :image, "Image" %>
    <%= f.text_field :image %>
  </div>
  <div class="form-group">
    <%= f.label :url, "Website" %>
    <%= f.text_field :url %>
  </div>
  <div class="form-group">
    <%= f.label :category, "Category" %>
    <%= f.select :category, @categories %>
  </div>
  <div class="field">
      <%= f.label :state%>
      <%= f.select :location, @states %>
  </div>
  <div class="field">
    <%= f.label :city%>
    <%= f.select :location, @cities %>
  </div>
  <div class="form-group">
    <%= f.label :address, "Address" %>
    <%= f.text_field :address %>
  </div>

  <div class="actions"><%= f.submit class: "btn btn-primary", method: :update %></div>
<% end %>
</div>

app/views/goodspots/index.html.erb
<div class="container">
  <%= form_tag goodspots_path, method: :get do %>
    <%= label_tag(:location, "Browse by Location") %>
    <%= select_tag :location, options_for_select(@locations_options, params[:location]), include_blank: true %>
    <%= label_tag(:category, "Browse by Category") %>
    <%= select_tag :category, options_for_select(@categories, params[:category]), :include_blank => true %>
    <%= submit_tag "Go!", class: "btn btn-primary" %>
  <% end %>

  <div class="row">
    <% @goodspots.each do |gs| %>
    <div class="col-lg-3 col-med-4 col-sm-6 col-xm-1 clearfix">
      <p><%= gs.name %></p>
      <p><%= link_to (image_tag (gs.image), :class => "img-responsive"), goodspot_path(gs.id) %></p>
    </div>
  <% end %>
  </div>
</div>

app/views/goodspots/new.html.erb
<h1>Add Your Goodspot!</h1>


<div class="container">
  <%= form_for @goodspot do |f| %>


    <% if @goodspot.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @goodspot.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <div class="field">
      <%= f.label :name, "Title" %>
      <%= f.text_field :name %>
    </div>


    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>


    <div class="form-group">
      <%= f.label :image, "Image" %>
      <%= f.text_field :image %>
    </div>


    <div class="form-group">
      <%= f.label :url, "URL" %>
      <%= f.text_field :url %>
    </div>


    <div class="field">
      <%= f.label :state%>
      <%= f.select :location, @states %>
    </div>


    <div class="field">
      <%= f.label :city%>
      <%= f.select :location, @cities %>
    </div>


    <div class="field">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>


    <div class="field">
      <%= f.label :category %>
      <%= f.select :category, @categories %>
    </div>

    <div class="actions"><%= f.submit %></div>
  <% end %>
</div>

app/views/goodspots/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="container show">
  <p><%= @goodspot.name + ' / ' + @goodspot.category%></p>
  <p><%= image_tag(@goodspot.image) %> </p>
  <p> <%=label_tag :username,"User:"%><%=link_to @goodspot.user.username, user_path(@goodspot.user.id) %></p>
  <p><%=label_tag :description,"Description:"%><%=@goodspot.description%></p>
  <% if @goodspot.address %>
    <p><%=label_tag :address,"Address:"%><%=@goodspot.address %></p>
  <% end %>
  <%if @goodspot.url %>
    <p><%=label_tag :url,"Website:"%><%=link_to @goodspot.url, @goodspot.url, :target => 'blank' %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodayApp</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



  <div class= "container header">
    <header>
      <h1>GOODAY!</h1>
    </header>
  </div>



  <nav class="navbar navbar-inverse">
      <div class="container">
        <% if current_user %>

          <div class="user_logout">
            Welcome, <%= current_user.username %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to 'Logout', session_path('dummy'), method: :delete %>
         </div>

        <div class="navbtns">
          <a class="btn btn-primary" href="<%=user_path(current_user)%>" role="button">Profile</a>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <a class="btn btn-primary" href="/goodspots" role="button">Browse</a>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <a class="btn btn-primary" href="/goodspots/new" role="button">Post</a>
        </div>


        <% else %>
          <%= link_to 'Login', login_path %>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to 'Sign Up', new_user_path %>
        <% end %>
      </div>
  </nav>

<selection>

<%= yield %>

</selection>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<div class="container">
<%= form_for @user, class: "form-horizontal center" do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :email, "Email" %>
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :username, "Username" %>
    <%= f.text_field :username %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, "Confirm Pass" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit class: "btn btn-primary" %></div>
<% end %>
</div>

app/views/users/show.html.erb
  <h1> Here Are Your Goodspots </h1>


<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="container">
  <% @user.goodspots.each do |gs| %>
    <% if @user.id == session[:user_id] %>
      <p><%= gs.name + ' / ' + gs.category %></p>
      <p><%= link_to (image_tag (gs.image), :class => "img-responsive user-post"), goodspot_path(gs.id) %></p>
      <%= button_to "Update", edit_goodspot_path(gs), method: :get %>
      <%= button_to "Delete Goodspot", goodspot_path(gs), method: :delete %>
    <% else %>
      <p><%= gs.name + ' / ' + gs.category %></p>
      <p><%= link_to (image_tag (gs.image)), goodspot_path(gs.id) %></p>
    <% end %>

  <% end %>
</div>

<% if @user.id == session[:user_id] %>
<%= button_to 'Delete Account', user_path, method: :delete %>
<% end %>